application:
  name: marketing-sacha-house
  port: 3000
  healthPath: /

environments:
  staging:
    domain: staging.marketing.sacha.house
    noIndex: true
  production:
    domain: marketing.sacha.house

resources:
  cpu: 200
  memory: 128
